[versions]
agp = "9.2.1"
junit = "4.13.2"
libxposed = "102.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "libxposed" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "libxposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
